### PR TITLE
New updates

### PR DESCRIPTION
**Pull request by nleroy917**
Hey!

Small iteration on top of what I already had going..

### For the core rust package:
As mentioned before, I kept the two binary crates and added a library crate. The library crate has two modules: 1) `checksum` and 2) `gc_count`. All the actual *logic* for computing checksums and gc-count lives in these modules in the library crate. The binary crates now import the necessary functions and add some "glue" (the CLI you made) to make it work via the command line. This approach is nice because it's modular and lets other things import that logic and reuse it. For example...

### The python bindings
These are their own self-contained crate inside the `bindings` folder. They leverage the library crate mentioned before and just import that code and then add more "glue" to make it all interface nicely with Python. You can see in the `Cargo.toml` I'm adding `rust_gc_count` as a dependency and just pointing one directory up...
```toml
rust_gc_count = { path = "../" }
```

Finally, I added python bindings for writing gc counts to a wiggle file like you had before in the CLI, but now you can do it from within python. I also added some type hinting and doc strings using [stub files](https://mypy.readthedocs.io/en/stable/stubs.html) to make it more user-friendly :)

<div align="center">
image
</div>

Let me know if you have questions or suggestions for improvement!

### CODE REVIEW

**Review by andrewyatz — APPROVED** [review]
As far as I can tell looks great to me

**Comment by andrewyatz** [comment]
FYI all up on PyPI now https://pypi.org/project/gc-count/

**Comment by nleroy917** [comment]
Thats amazing. I dont think I've ever had a github action just work the first time 😂 I just tested it locally and it all seems to function

**Comment by andrewyatz** [comment]
I was also similarly amazed that it just worked. Absolutely brilliant

**Pull request merged**
