### PR TITLE
Start python bindings

### PR DESCRIPTION
**Pull request by nleroy917**
Hi @andrewyatz,

I'm a grad student in @nsheff's lab, and he said he's using the checksum calculator in one of the sequence collections pipelines. He pointed me at the implementation, and it looks like its using [subprocess calls](https://github.com/refgenie/seqcolapi/blob/c39bac871561302f3f8190c28fd939f14439e1c0/analysis/pipeline/add_to_seqcol_server.py#L61-L63) because this crate is only offered as a cli. I thought this was a great opportunity for some python bindings using [`pyo3`](https://pyo3.rs/v0.20.2/).

I implemented basic Python bindings for just checksum calculation. I did a few things to achieve this:
1. Converted your core **binary** crate to a **library + binary** crate to abstract away the `process_sequence` function.
2. Change the `checksumseq` binary crate to import this new library crate.
3. I added a new `bindings` folder, which contains a new library crate following the [`maturin` docs](https://www.maturin.rs/).
4. The bindings crate now imports the original library crate.
5. Fixed some things where I saw [`clippy` warnings](https://doc.rust-lang.org/nightly/clippy/).

The bindings don't change any implementation of the core code, it just imports it and uses it.

## To install and use in python
There are several ways to achieve this but the easiest is probably:

1. Create a new python environment
```console
python -m venv venv
source venv/bin/activate
```
2. Install `maturin`, the companion package to `pyo3`.
```console
pip install maturin
```
3. Navigate to `rust_gc_count/bindings`
4. Install the package:
```python
maturin build
```
5. Use!
```python
from gc_count import checksum

results = checksum("path/to/seqs.fasta")
for result in results:
    print(result.sha512)
```

### CODE REVIEW

**Comment by andrewyatz** [comment]
This is fantastic to read and review. Very happy to bring this in as a library especially as it supports your work. My only additional request on top of what you've done here is to add the details above about installing the library in Python to `README.md`. Is that okay?

**Comment by nleroy917** [comment]
yeah! I will definitely add some python installation details. It will depend on how you want to distribute it. Theres a continuous integration yaml file that will auto-build wheels for all sorts of architectures and upload to pypi so one can just `pip install`...

... but that might be overkill. I don't want to add something that's going to eat into your GitHub actions minutes. @nsheff might be able to weigh in if he's got any requirements for how he builds/runs those pipelines.

**Comment by andrewyatz** [comment]
I can see maturin has put in a CI file, so I'm kinda happy for this to get uploaded to pypi and from the CI file generated it looks like I need to set a secret called `PYPI_API_TOKEN`. Yeah why not upload to PyPI as that's the most useful place right

**Comment by nleroy917** [comment]
Yeah, if that's ok with you. I'll still remove some of the obscure architectures it builds for (`armv7, s390x, ppc64le`) to save time and resource usage (unless you want those). Also, you might not need an API token for this. According to [their docs](https://www.maturin.rs/distribution#using-pypis-trusted-publishing), I believe this workflow supports using the [PyPi trusted publisher](https://docs.pypi.org/trusted-publishers/) workflow. So it's just a matter of linking the repo to the PyPi project.

Steps are probably:
1. [make new pypi package](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/), name it whatever you want
2. Link to this repo
3. Run the workflow?

I think we just need to make sure the names are consistent. I called the python package `gc_count` because `import rust_gc_count` didn't feel right for python 😵‍💫

**Comment by andrewyatz** [comment]
Sounds good to me. Just created one called `gc_count` which is now in my pypi as the trusted environment. As for the architectures I did wonder about ARM but that's covered by `aarch64`. Otherwise I think we're good

Thank you

**Comment by nleroy917** [comment]
yeah `armv7` is like, raspberry pis I think.

I made some updates to the workflow file and moved it to the root of the project. If we merge and then make a release, it will probably run the workflow and try to push to PyPi. Debugging github workflow files is always fun 🥲

**Comment by andrewyatz** [comment]
Okay going to merge and make a release. Wish us luck

**Comment by andrewyatz** [comment]
One thing I just realised, the repo is currently licensed to EMBL. I believe your contributions should be linked to yourself or to UVA. Can you let me know what it should be and we'll add it to NOTICE and flag the appropriate bits of code

**Comment by andrewyatz** [comment]
FYI I just realised the bindings are in a sub-directory so GitHub won't pick up on the CI right away. Will take a look later on today and see what I need to prod

**Comment by nleroy917** [comment]
> FYI I just realised the bindings are in a sub-directory

Ah shoot, I recognized this too and moved it the project root. I committed the changes but never actually pushed them 🙃 Sorry about that. I can do another PR if you'd like or just let you take over. I pasted the most recent workflow file below. I got it setup to run each action inside the `bindings` directory.

Re: 
>  believe your contributions should be linked to yourself or to UVA

I can get back to you on this one ASAP..

```yaml
# This file is autogenerated by maturin v1.2.3
# To update, run
#
#    maturin generate-ci github
#
name: CI

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, x86, aarch64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
          working-directory: ./bindings
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./bindings/dist

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: ${{ matrix.target }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          working-directory: ./bindings
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./bindings/dist

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          working-directory: ./bindings
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./bindings/dist

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: ./bindings
      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./bindings/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [linux, windows, macos, sdist]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./bindings/dist
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --non-interactive --skip-existing ./bindings/dist/*
```

**Comment by andrewyatz** [comment]
I think start up a fresh PR with the changes and with your contributions too and let's build on these that you've done. Thanks for being so understanding

**Pull request merged**
